/*     */ package moze_intel.projecte.utils.text;
/*     */ 
/*     */ import moze_intel.projecte.PECore;
/*     */ import net.minecraft.Util;
/*     */ 
/*     */ public enum PELang
/*     */   implements ILangEntry {
/*   8 */   UNKNOWN_ITEM("argument.item.id.invalid"),
/*   9 */   UNKNOWN_TAG("arguments.item.tag.unknown"),
/*     */   
/*  11 */   PROJECTE("misc", "mod_name"),
/*  12 */   PACK_DESCRIPTION("misc", "pack_description"),
/*  13 */   SECONDS("misc", "seconds"),
/*  14 */   EVERY_TICK("misc", "seconds.every_tick"),
/*  15 */   HIGH_ALCHEMIST("misc", "high_alchemist_joined"),
/*  16 */   UPDATE_AVAILABLE("misc", "update.available"),
/*  17 */   UPDATE_GET_IT("misc", "update.get_it"),
/*  18 */   BLACKLIST("misc", "blacklist"),
/*  19 */   WHITELIST("misc", "whitelist"),
/*  20 */   DENSITY_MODE_TARGET("misc", "mode_switch"),
/*     */   
/*  22 */   CLEAR_KNOWLEDGE_NOTIFY("command", "clear_knowledge.notify"),
/*  23 */   CLEAR_KNOWLEDGE_SUCCESS("command", "clear_knowledge.success"),
/*  24 */   DUMP_MISSING_EMC_NONE_MISSING("command", "dump_missing_emc.none_missing"),
/*  25 */   DUMP_MISSING_EMC_ONE_MISSING("command", "dump_missing_emc.one_missing"),
/*  26 */   DUMP_MISSING_EMC_MULTIPLE_MISSING("command", "dump_missing_emc.multiple_missing"),
/*  27 */   COMMAND_INVALID_ITEM("command", "emc.invalid_item"),
/*  28 */   COMMAND_NO_ITEM("command", "emc.no_item"),
/*  29 */   COMMAND_REMOVE_SUCCESS("command", "remove.success"),
/*  30 */   COMMAND_RESET_SUCCESS("command", "reset.success"),
/*  31 */   COMMAND_SET_SUCCESS("command", "set.success"),
/*  32 */   COMMAND_EMC_INVALID("command", "emc.invalid"),
/*  33 */   COMMAND_EMC_NEGATIVE("command", "emc.negative"),
/*  34 */   COMMAND_EMC_ADD_SUCCESS("command", "emc.add.success"),
/*  35 */   COMMAND_EMC_REMOVE_SUCCESS("command", "emc.remove.success"),
/*  36 */   COMMAND_EMC_SET_SUCCESS("command", "emc.set.success"),
/*  37 */   COMMAND_EMC_GET_SUCCESS("command", "emc.get.success"),
/*  38 */   COMMAND_EMC_TEST_SUCCESS("command", "emc.test.success"),
/*  39 */   COMMAND_EMC_TEST_FAIL("command", "emc.test.fail"),
/*  40 */   COMMAND_KNOWLEDGE_INVALID("command", "knowledge.invalid"),
/*  41 */   COMMAND_KNOWLEDGE_CLEAR_SUCCESS("command", "knowledge.clear.success"),
/*  42 */   COMMAND_KNOWLEDGE_CLEAR_FAIL("command", "knowledge.clear.fail"),
/*  43 */   COMMAND_KNOWLEDGE_LEARN_SUCCESS("command", "knowledge.learn.success"),
/*  44 */   COMMAND_KNOWLEDGE_LEARN_FAIL("command", "knowledge.learn.fail"),
/*  45 */   COMMAND_KNOWLEDGE_UNLEARN_SUCCESS("command", "knowledge.unlearn.success"),
/*  46 */   COMMAND_KNOWLEDGE_UNLEARN_FAIL("command", "knowledge.unlearn.fail"),
/*  47 */   COMMAND_KNOWLEDGE_TEST_SUCCESS("command", "knowledge.test.success"),
/*  48 */   COMMAND_KNOWLEDGE_TEST_FAIL("command", "knowledge.test.fail"),
/*  49 */   COMMAND_PROVIDER_FAIL("command", "provider.fail"),
/*  50 */   RELOAD_NOTICE("command", "reload.notice"),
/*  51 */   SHOWBAG_NOT_FOUND("command", "showbag.offline.notfound"),
/*  52 */   SHOWBAG_NAMED("command", "showbag.named"),
/*     */   
/*  54 */   DIVINING_AVG_EMC("divining_rod", "avg_emc"),
/*  55 */   DIVINING_MAX_EMC("divining_rod", "max_emc"),
/*  56 */   DIVINING_SECOND_MAX("divining_rod", "second_max"),
/*  57 */   DIVINING_THIRD_MAX("divining_rod", "third_max"),
/*  58 */   DIVINING_RANGE_3("divining_rod", "range.3"),
/*  59 */   DIVINING_RANGE_16("divining_rod", "range.16"),
/*  60 */   DIVINING_RANGE_64("divining_rod", "range.64"),
/*     */   
/*  62 */   EMC("emc", "emc"),
/*  63 */   EMC_MAX_GEN_RATE("emc", "max_gen_rate"),
/*  64 */   EMC_MAX_OUTPUT_RATE("emc", "max_output_rate"),
/*  65 */   EMC_MAX_STORAGE("emc", "max_storage"),
/*  66 */   EMC_STORED("emc", "stored"),
/*  67 */   EMC_HAS_KNOWLEDGE("emc", "has_knowledge"),
/*  68 */   EMC_NO_KNOWLEDGE("emc", "no_knowledge"),
/*  69 */   EMC_TOOLTIP("emc", "tooltip"),
/*  70 */   EMC_STACK_TOOLTIP("emc", "tooltip.stack"),
/*  71 */   EMC_TOOLTIP_WITH_SELL("emc", "tooltip.with_sell"),
/*  72 */   EMC_STACK_TOOLTIP_WITH_SELL("emc", "tooltip.stack.with_sell"),
/*  73 */   EMC_TOO_MUCH("emc", "too_much"),
/*     */   
/*  75 */   JEI_COLLECTOR("jei", "collector"),
/*  76 */   WORLD_TRANSMUTE("jei", "world_transmute"),
/*  77 */   WORLD_TRANSMUTE_DESCRIPTION("jei", "world_transmute.description"),
/*     */   
/*  79 */   CURIOS_KLEIN_STAR("curios.identifier.klein_star"),
/*     */   
/*  81 */   GEM_ENABLED("gem", "enabled"),
/*  82 */   GEM_DISABLED("gem", "disabled"),
/*  83 */   GEM_ACTIVATE("gem", "activate"),
/*  84 */   GEM_DEACTIVATE("gem", "deactivate"),
/*  85 */   NIGHT_VISION("gem", "night_vision"),
/*  86 */   NIGHT_VISION_PROMPT("gem", "night_vision.prompt"),
/*  87 */   STEP_ASSIST("gem", "step_assist"),
/*  88 */   STEP_ASSIST_PROMPT("gem", "step_assist.prompt"),
/*  89 */   GEM_LORE_FEET("gem", "lore.feet"),
/*  90 */   GEM_LORE_LEGS("gem", "lore.legs"),
/*  91 */   GEM_LORE_CHEST("gem", "lore.chest"),
/*  92 */   GEM_LORE_HELM("gem", "lore.helm"),
/*     */   
/*  94 */   GUI_DARK_MATTER_FURNACE("gui", "dark_matter_furnace.shortname"),
/*  95 */   GUI_RED_MATTER_FURNACE("gui", "red_matter_furnace.shortname"),
/*  96 */   GUI_RELAY_MK1("gui", "relay.mk1"),
/*  97 */   GUI_RELAY_MK2("gui", "relay.mk2"),
/*  98 */   GUI_RELAY_MK3("gui", "relay.mk3"),
/*     */   
/* 100 */   CURRENT_MODE("mode", "current"),
/* 101 */   INVALID_MODE("mode", "invalid"),
/* 102 */   MODE_SWITCH("mode", "switch"),
/* 103 */   MODE_ARCANA_1("mode", "arcana.1"),
/* 104 */   MODE_ARCANA_2("mode", "arcana.2"),
/* 105 */   MODE_ARCANA_3("mode", "arcana.3"),
/* 106 */   MODE_ARCANA_4("mode", "arcana.4"),
/* 107 */   MODE_KATAR_1("mode", "katar.1"),
/* 108 */   MODE_KATAR_2("mode", "katar.2"),
/* 109 */   MODE_MERCURIAL_EYE_1("mode", "mercurial_eye.1"),
/* 110 */   MODE_MERCURIAL_EYE_2("mode", "mercurial_eye.2"),
/* 111 */   MODE_MERCURIAL_EYE_3("mode", "mercurial_eye.3"),
/* 112 */   MODE_MERCURIAL_EYE_4("mode", "mercurial_eye.4"),
/* 113 */   MODE_MERCURIAL_EYE_5("mode", "mercurial_eye.5"),
/* 114 */   MODE_MERCURIAL_EYE_6("mode", "mercurial_eye.6"),
/* 115 */   MODE_MORNING_STAR_1("mode", "morning_star.1"),
/* 116 */   MODE_MORNING_STAR_2("mode", "morning_star.2"),
/* 117 */   MODE_MORNING_STAR_3("mode", "morning_star.3"),
/* 118 */   MODE_MORNING_STAR_4("mode", "morning_star.4"),
/* 119 */   MODE_PHILOSOPHER_1("mode", "philosopher.1"),
/* 120 */   MODE_PHILOSOPHER_2("mode", "philosopher.2"),
/* 121 */   MODE_PHILOSOPHER_3("mode", "philosopher.3"),
/* 122 */   MODE_PICK_1("mode", "pick.1"),
/* 123 */   MODE_PICK_2("mode", "pick.2"),
/* 124 */   MODE_PICK_3("mode", "pick.3"),
/* 125 */   MODE_PICK_4("mode", "pick.4"),
/* 126 */   MODE_RED_SWORD_1("mode", "red_sword.1"),
/* 127 */   MODE_RED_SWORD_2("mode", "red_sword.2"),
/*     */   
/* 129 */   PEDESTAL_DISABLED("pedestal", "item_disabled"),
/* 130 */   PEDESTAL_ON("pedestal", "on_pedestal"),
/* 131 */   PEDESTAL_TOOLTIP1("pedestal", "tooltip.1"),
/* 132 */   PEDESTAL_TOOLTIP2("pedestal", "tooltip.2"),
/* 133 */   PEDESTAL_ARCHANGEL_1("pedestal", "archangel.1"),
/* 134 */   PEDESTAL_ARCHANGEL_2("pedestal", "archangel.2"),
/* 135 */   PEDESTAL_BLACK_HOLE_BAND_1("pedestal", "black_hole_band.1"),
/* 136 */   PEDESTAL_BLACK_HOLE_BAND_2("pedestal", "black_hole_band.2"),
/* 137 */   PEDESTAL_BODY_STONE_1("pedestal", "body_stone.1"),
/* 138 */   PEDESTAL_BODY_STONE_2("pedestal", "body_stone.2"),
/* 139 */   PEDESTAL_EVERTIDE_1("pedestal", "evertide.1"),
/* 140 */   PEDESTAL_EVERTIDE_2("pedestal", "evertide.2"),
/* 141 */   PEDESTAL_HARVEST_GODDESS_1("pedestal", "harvest_goddess.1"),
/* 142 */   PEDESTAL_HARVEST_GODDESS_2("pedestal", "harvest_goddess.2"),
/* 143 */   PEDESTAL_HARVEST_GODDESS_3("pedestal", "harvest_goddess.3"),
/* 144 */   PEDESTAL_IGNITION_1("pedestal", "ignition.1"),
/* 145 */   PEDESTAL_IGNITION_2("pedestal", "ignition.2"),
/* 146 */   PEDESTAL_LIFE_STONE_1("pedestal", "life_stone.1"),
/* 147 */   PEDESTAL_LIFE_STONE_2("pedestal", "life_stone.2"),
/* 148 */   PEDESTAL_MIND_STONE("pedestal", "mind_stone"),
/* 149 */   PEDESTAL_REPAIR_TALISMAN_1("pedestal", "repair_talisman.1"),
/* 150 */   PEDESTAL_REPAIR_TALISMAN_2("pedestal", "repair_talisman.2"),
/* 151 */   PEDESTAL_SOUL_STONE_1("pedestal", "soul_stone.1"),
/* 152 */   PEDESTAL_SOUL_STONE_2("pedestal", "soul_stone.2"),
/* 153 */   PEDESTAL_SWRG_1("pedestal", "swrg.1"),
/* 154 */   PEDESTAL_SWRG_2("pedestal", "swrg.2"),
/* 155 */   PEDESTAL_TIME_WATCH_1("pedestal", "time_watch.1"),
/* 156 */   PEDESTAL_TIME_WATCH_2("pedestal", "time_watch.2"),
/* 157 */   PEDESTAL_VOLCANITE_1("pedestal", "volcanite.1"),
/* 158 */   PEDESTAL_VOLCANITE_2("pedestal", "volcanite.2"),
/* 159 */   PEDESTAL_ZERO_1("pedestal", "zero.1"),
/* 160 */   PEDESTAL_ZERO_2("pedestal", "zero.2"),
/* 161 */   PEDESTAL_ZERO_3("pedestal", "zero.3"),
/*     */   
/* 163 */   TIME_WATCH_DISABLED("time_watch", "disabled"),
/* 164 */   TIME_WATCH_MODE("time_watch", "mode"),
/* 165 */   TIME_WATCH_MODE_SWITCH("time_watch", "mode_switch"),
/* 166 */   TIME_WATCH_OFF("time_watch", "off"),
/* 167 */   TIME_WATCH_FAST_FORWARD("time_watch", "fast_forward"),
/* 168 */   TIME_WATCH_REWIND("time_watch", "rewind"),
/*     */   
/* 170 */   TOOLTIP_ARCANA_INACTIVE("tooltip", "arcana.inactive"),
/* 171 */   TOOLTIP_EVERTIDE_1("tooltip", "evertide.1"),
/* 172 */   TOOLTIP_EVERTIDE_2("tooltip", "evertide.2"),
/* 173 */   TOOLTIP_EVERTIDE_3("tooltip", "evertide.3"),
/* 174 */   TOOLTIP_EVERTIDE_4("tooltip", "evertide.4"),
/* 175 */   TOOLTIP_GEM_DENSITY_1("tooltip", "gem_density.1"),
/* 176 */   TOOLTIP_GEM_DENSITY_2("tooltip", "gem_density.2"),
/* 177 */   TOOLTIP_GEM_DENSITY_3("tooltip", "gem_density.3"),
/* 178 */   TOOLTIP_GEM_DENSITY_4("tooltip", "gem_density.4"),
/* 179 */   TOOLTIP_GEM_DENSITY_5("tooltip", "gem_density.5"),
/* 180 */   TOOLTIP_PHILOSTONE("tooltip", "philostone"),
/* 181 */   TOOLTIP_STORED_XP("tooltip", "stored_xp"),
/* 182 */   TOOLTIP_TIME_WATCH_1("tooltip", "time_watch.1"),
/* 183 */   TOOLTIP_TIME_WATCH_2("tooltip", "time_watch.2"),
/* 184 */   TOOLTIP_TOME("tooltip", "tome"),
/* 185 */   TOOLTIP_VOLCANITE_1("tooltip", "volcanite.1"),
/* 186 */   TOOLTIP_VOLCANITE_2("tooltip", "volcanite.2"),
/* 187 */   TOOLTIP_VOLCANITE_3("tooltip", "volcanite.3"),
/* 188 */   TOOLTIP_VOLCANITE_4("tooltip", "volcanite.4"),
/*     */   
/* 190 */   TRANSMUTATION_TRANSMUTE("transmutation", "transmute"),
/* 191 */   TRANSMUTATION_LEARNED_1("transmutation", "learned.1"),
/* 192 */   TRANSMUTATION_LEARNED_2("transmutation", "learned.2"),
/* 193 */   TRANSMUTATION_LEARNED_3("transmutation", "learned.3"),
/* 194 */   TRANSMUTATION_LEARNED_4("transmutation", "learned.4"),
/* 195 */   TRANSMUTATION_LEARNED_5("transmutation", "learned.5"),
/* 196 */   TRANSMUTATION_LEARNED_6("transmutation", "learned.6"),
/* 197 */   TRANSMUTATION_LEARNED_7("transmutation", "learned.7"),
/* 198 */   TRANSMUTATION_LEARNED_8("transmutation", "learned.8"),
/* 199 */   TRANSMUTATION_UNLEARNED_1("transmutation", "unlearned.1"),
/* 200 */   TRANSMUTATION_UNLEARNED_2("transmutation", "unlearned.2"),
/* 201 */   TRANSMUTATION_UNLEARNED_3("transmutation", "unlearned.3"),
/* 202 */   TRANSMUTATION_UNLEARNED_4("transmutation", "unlearned.4"),
/* 203 */   TRANSMUTATION_UNLEARNED_5("transmutation", "unlearned.5"),
/* 204 */   TRANSMUTATION_UNLEARNED_6("transmutation", "unlearned.6"),
/* 205 */   TRANSMUTATION_UNLEARNED_7("transmutation", "unlearned.7"),
/* 206 */   TRANSMUTATION_UNLEARNED_8("transmutation", "unlearned.8"),
/* 207 */   TRANSMUTATION_UNLEARNED_9("transmutation", "unlearned.9"),
/*     */   
/* 209 */   ADVANCEMENTS_PROJECTE_DESCRIPTION("advancements", "description"),
/* 210 */   ADVANCEMENTS_PHILO_STONE("advancements", "philo_stone"),
/* 211 */   ADVANCEMENTS_PHILO_STONE_DESCRIPTION("advancements", "philo_stone.description"),
/* 212 */   ADVANCEMENTS_TRANSMUTATION_TABLE("advancements", "transmutation_table"),
/* 213 */   ADVANCEMENTS_TRANSMUTATION_TABLE_DESCRIPTION("advancements", "transmutation_table.description"),
/* 214 */   ADVANCEMENTS_TRANSMUTATION_TABLET("advancements", "transmutation_tablet"),
/* 215 */   ADVANCEMENTS_TRANSMUTATION_TABLET_DESCRIPTION("advancements", "transmutation_tablet.description"),
/* 216 */   ADVANCEMENTS_KLEIN_STAR("advancements", "klein_star"),
/* 217 */   ADVANCEMENTS_KLEIN_STAR_DESCRIPTION("advancements", "klein_star.description"),
/* 218 */   ADVANCEMENTS_KLEIN_STAR_BIG("advancements", "klein_star_big"),
/* 219 */   ADVANCEMENTS_KLEIN_STAR_BIG_DESCRIPTION("advancements", "klein_star_big.description"),
/* 220 */   ADVANCEMENTS_ALCH_CHEST("advancements", "alch_chest"),
/* 221 */   ADVANCEMENTS_ALCH_CHEST_DESCRIPTION("advancements", "alch_chest.description"),
/* 222 */   ADVANCEMENTS_ALCH_BAG("advancements", "alch_bag"),
/* 223 */   ADVANCEMENTS_ALCH_BAG_DESCRIPTION("advancements", "alch_bag.description"),
/* 224 */   ADVANCEMENTS_CONDENSER("advancements", "condenser"),
/* 225 */   ADVANCEMENTS_CONDENSER_DESCRIPTION("advancements", "condenser.description"),
/* 226 */   ADVANCEMENTS_COLLECTOR("advancements", "collector"),
/* 227 */   ADVANCEMENTS_COLLECTOR_DESCRIPTION("advancements", "collector.description"),
/* 228 */   ADVANCEMENTS_RELAY("advancements", "relay"),
/* 229 */   ADVANCEMENTS_RELAY_DESCRIPTION("advancements", "relay.description"),
/* 230 */   ADVANCEMENTS_DARK_MATTER("advancements", "dark_matter"),
/* 231 */   ADVANCEMENTS_DARK_MATTER_DESCRIPTION("advancements", "dark_matter.description"),
/* 232 */   ADVANCEMENTS_DARK_MATTER_PICKAXE("advancements", "dark_matter_pickaxe"),
/* 233 */   ADVANCEMENTS_DARK_MATTER_PICKAXE_DESCRIPTION("advancements", "dark_matter_pickaxe.description"),
/* 234 */   ADVANCEMENTS_DARK_MATTER_BLOCK("advancements", "dark_matter_block"),
/* 235 */   ADVANCEMENTS_DARK_MATTER_BLOCK_DESCRIPTION("advancements", "dark_matter_block.description"),
/* 236 */   ADVANCEMENTS_DARK_MATTER_FURNACE("advancements", "dark_matter_furnace"),
/* 237 */   ADVANCEMENTS_DARK_MATTER_FURNACE_DESCRIPTION("advancements", "dark_matter_furnace.description"),
/* 238 */   ADVANCEMENTS_RED_MATTER("advancements", "red_matter"),
/* 239 */   ADVANCEMENTS_RED_MATTER_DESCRIPTION("advancements", "red_matter.description"),
/* 240 */   ADVANCEMENTS_RED_MATTER_PICKAXE("advancements", "red_matter_pickaxe"),
/* 241 */   ADVANCEMENTS_RED_MATTER_PICKAXE_DESCRIPTION("advancements", "red_matter_pickaxe.description"),
/* 242 */   ADVANCEMENTS_RED_MATTER_BLOCK("advancements", "red_matter_block"),
/* 243 */   ADVANCEMENTS_RED_MATTER_BLOCK_DESCRIPTION("advancements", "red_matter_block.description"),
/* 244 */   ADVANCEMENTS_RED_MATTER_FURNACE("advancements", "red_matter_furnace"),
/* 245 */   ADVANCEMENTS_RED_MATTER_FURNACE_DESCRIPTION("advancements", "red_matter_furnace.description");
/*     */ 
/*     */ 
/*     */   
/*     */   private final String key;
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   PELang(String key) {
/* 255 */     this.key = key;
/*     */   }
/*     */ 
/*     */   
/*     */   public String getTranslationKey() {
/* 260 */     return this.key;
/*     */   }
/*     */ }


/* Location:              C:\Users\Brent\Downloads\ProjectE-1.20.1-PE1.0.1.jar!\moze_intel\project\\utils\text\PELang.class
 * Java compiler version: 17 (61.0)
 * JD-Core Version:       1.1.3
 */